import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/globals.css'
import { rubik } from "@/styles/font";
import { cairo } from '@/styles/font';
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Versus Website',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${rubik.variable} ${cairo.variable}`}>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
